/* AIMasterTools AI Directory — Tool Data
   100 tools across 10 categories
   Last updated: April 2026
*/

const AI_TOOLS = [
  // ── WRITING ──────────────────────────────────────────────────
  {
    id: "jasper",
    name: "Jasper AI",
    category: "writing",
    tagline: "Enterprise AI copywriting platform",
    description: "Jasper is the leading AI writing platform for marketing teams. Create blog posts, ads, social content, and email campaigns with brand-voice controls and team collaboration.",
    pricing: "From $49/mo",
    pricingTier: "paid",
    rating: 9.0,
    features: ["Brand voice settings", "50+ templates", "SEO mode", "Team collaboration", "Plagiarism checker"],
    url: "https://www.jasper.ai",
    affiliate: true,
    featured: false
  },
  {
    id: "copyai",
    name: "Copy.ai",
    category: "writing",
    tagline: "AI-powered marketing copy at scale",
    description: "Copy.ai automates your marketing workflows — from blog drafts to cold emails. The free plan is generous, and the Go plan unlocks unlimited words.",
    pricing: "Free / From $36/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["Unlimited words (paid)", "90+ content types", "Workflow automation", "Brand voice", "API access"],
    url: "https://www.copy.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "writesonic",
    name: "Writesonic",
    category: "writing",
    tagline: "Fast AI content generation for SEO",
    description: "Writesonic produces SEO-optimized articles, landing pages, and product descriptions. Chatsonic adds real-time web access for fresh content.",
    pricing: "From $20/mo",
    pricingTier: "paid",
    rating: 8.3,
    features: ["Real-time web data (Chatsonic)", "SEO integration", "Bulk generation", "25+ languages", "AI article writer"],
    url: "https://writesonic.com",
    affiliate: false,
    featured: false
  },
  {
    id: "grammarly",
    name: "Grammarly",
    category: "writing",
    tagline: "AI writing assistant for clarity and correctness",
    description: "Grammarly checks grammar, style, and tone across every platform you write on — browser, Word, Google Docs, and more. GrammarlyGO adds generative AI.",
    pricing: "Free / From $12/mo",
    pricingTier: "freemium",
    rating: 9.1,
    features: ["Real-time grammar checks", "Tone detection", "GrammarlyGO (gen AI)", "Plagiarism detection", "Works everywhere"],
    url: "https://www.grammarly.com",
    affiliate: false,
    featured: false
  },
  {
    id: "quillbot",
    name: "QuillBot",
    category: "writing",
    tagline: "AI paraphrasing and summarization",
    description: "QuillBot's paraphraser rewrites sentences while preserving meaning. Ideal for students, writers, and non-native speakers who need polished prose.",
    pricing: "Free / From $9.99/mo",
    pricingTier: "freemium",
    rating: 8.4,
    features: ["7 paraphrase modes", "Summarizer", "Grammar checker", "Citation generator", "Word flipper"],
    url: "https://quillbot.com",
    affiliate: false,
    featured: false
  },
  {
    id: "rytr",
    name: "Rytr",
    category: "writing",
    tagline: "Affordable AI writer for solopreneurs",
    description: "Rytr is one of the most affordable AI writing tools, offering 40+ use-case templates and a capable editor at a low price point.",
    pricing: "Free / From $9/mo",
    pricingTier: "freemium",
    rating: 7.9,
    features: ["40+ use cases", "30+ languages", "SEO analyzer", "Custom tone", "Chrome extension"],
    url: "https://rytr.me",
    affiliate: false,
    featured: false
  },
  {
    id: "wordtune",
    name: "Wordtune",
    category: "writing",
    tagline: "AI rewriting and sentence improvement",
    description: "Wordtune rewrites your sentences to sound more natural, concise, or formal. Spices mode adds statistics, examples, and counterarguments automatically.",
    pricing: "Free / From $14.99/mo",
    pricingTier: "freemium",
    rating: 8.1,
    features: ["Rewrite modes", "Spices (auto-additions)", "Summarizer", "Read more widget", "Chrome extension"],
    url: "https://www.wordtune.com",
    affiliate: false,
    featured: false
  },
  {
    id: "hemingway",
    name: "Hemingway Editor",
    category: "writing",
    tagline: "Bold, clear writing in minutes",
    description: "Hemingway highlights complex sentences, passive voice, and adverbs so your writing becomes punchy and direct. Available as a web app and desktop app.",
    pricing: "$19.99 one-time (desktop)",
    pricingTier: "paid",
    rating: 8.0,
    features: ["Readability grade", "Passive voice detection", "Sentence complexity highlight", "Desktop app", "Distraction-free mode"],
    url: "https://hemingwayapp.com",
    affiliate: false,
    featured: false
  },
  {
    id: "anyword",
    name: "Anyword",
    category: "writing",
    tagline: "Performance-driven AI copywriting",
    description: "Anyword predicts the conversion impact of your copy before you publish. Built for performance marketers who want data-backed headlines and CTAs.",
    pricing: "From $49/mo",
    pricingTier: "paid",
    rating: 8.5,
    features: ["Predictive Performance Score", "A/B copy variants", "Ad copy generation", "Email subject lines", "Landing page copy"],
    url: "https://anyword.com",
    affiliate: false,
    featured: false
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "writing",
    tagline: "AI writing woven into your workspace",
    description: "Notion AI adds generative AI directly inside Notion pages — summarize docs, write first drafts, extract action items, and translate — without leaving your workspace.",
    pricing: "$10/mo add-on",
    pricingTier: "paid",
    rating: 8.7,
    features: ["Draft & summarize", "Action item extraction", "Translate", "Q&A over your docs", "Integrated in Notion"],
    url: "https://www.notion.so/product/ai",
    affiliate: false,
    featured: false
  },

  // ── CODING ──────────────────────────────────────────────────
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "coding",
    tagline: "The original AI pair programmer",
    description: "GitHub Copilot suggests whole lines and functions as you type, trained on billions of lines of public code. Integrates with VS Code, JetBrains, Neovim, and more.",
    pricing: "From $10/mo",
    pricingTier: "paid",
    rating: 9.2,
    features: ["Inline code suggestions", "Chat in editor", "PR summaries", "CLI integration", "Security scanning"],
    url: "https://github.com/features/copilot",
    affiliate: false,
    featured: false
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "coding",
    tagline: "AI-first code editor for power users",
    description: "Cursor is a VS Code fork with deep AI integration — chat with your codebase, apply multi-file edits, and run agents to complete features autonomously.",
    pricing: "Free / From $20/mo",
    pricingTier: "freemium",
    rating: 9.4,
    features: ["Codebase chat", "Multi-file edits", "Agent mode", "Tab autocomplete", "Custom rules"],
    url: "https://cursor.com",
    affiliate: false,
    featured: false
  },
  {
    id: "tabnine",
    name: "Tabnine",
    category: "coding",
    tagline: "Privacy-first AI code completion",
    description: "Tabnine offers whole-line and full-function completions with a strong focus on privacy — your code never leaves your environment on the self-hosted plan.",
    pricing: "Free / From $12/mo",
    pricingTier: "freemium",
    rating: 8.3,
    features: ["Self-hosted option", "Team learning mode", "30+ languages", "IDE plugins", "Code review chat"],
    url: "https://www.tabnine.com",
    affiliate: false,
    featured: false
  },
  {
    id: "replit",
    name: "Replit",
    category: "coding",
    tagline: "Build and deploy apps with AI in the browser",
    description: "Replit is a browser-based IDE with AI Agent that can build full apps from a text prompt. Great for prototyping, learning, and deploying side projects fast.",
    pricing: "Free / From $25/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["AI Agent (build from prompt)", "In-browser IDE", "One-click deploy", "Multiplayer coding", "Ghostwriter AI"],
    url: "https://replit.com",
    affiliate: false,
    featured: false
  },
  {
    id: "codeium",
    name: "Codeium",
    category: "coding",
    tagline: "Free AI coding superpower",
    description: "Codeium provides AI autocomplete and chat for free, supporting 70+ languages and 40+ IDE integrations. Windsurf is their AI-native editor.",
    pricing: "Free / From $10/mo (teams)",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["Free tier with no limits", "70+ languages", "Context-aware chat", "Windsurf editor", "Enterprise security"],
    url: "https://codeium.com",
    affiliate: false,
    featured: false
  },
  {
    id: "amazon-codewhisperer",
    name: "Amazon Q Developer",
    category: "coding",
    tagline: "AWS-native AI for cloud developers",
    description: "Amazon Q Developer (formerly CodeWhisperer) provides code suggestions optimized for AWS services, with free tier for individuals and security scanning built in.",
    pricing: "Free / From $19/mo",
    pricingTier: "freemium",
    rating: 8.0,
    features: ["AWS-optimized suggestions", "Security scanning", "Free for individuals", "VS Code + JetBrains", "CLI AI assistant"],
    url: "https://aws.amazon.com/q/developer/",
    affiliate: false,
    featured: false
  },
  {
    id: "sourcegraph-cody",
    name: "Sourcegraph Cody",
    category: "coding",
    tagline: "AI that understands your entire codebase",
    description: "Cody uses Sourcegraph's code intelligence graph to answer questions about your entire codebase — not just open files. Powerful for large monorepos.",
    pricing: "Free / From $9/mo",
    pricingTier: "freemium",
    rating: 8.2,
    features: ["Codebase-wide context", "Enterprise code graph", "Multi-LLM support", "VS Code + JetBrains", "Custom commands"],
    url: "https://sourcegraph.com/cody",
    affiliate: false,
    featured: false
  },
  {
    id: "aider",
    name: "Aider",
    category: "coding",
    tagline: "Open-source CLI AI coding agent",
    description: "Aider is a free, open-source AI pair programmer in your terminal. It edits files, runs tests, and commits changes automatically using Claude or GPT-4.",
    pricing: "Free (open source)",
    pricingTier: "free",
    rating: 8.9,
    features: ["Terminal-based", "Multi-file edits", "Auto git commits", "Works with Claude & GPT-4", "Voice coding mode"],
    url: "https://aider.chat",
    affiliate: false,
    featured: false
  },
  {
    id: "continue-dev",
    name: "Continue.dev",
    category: "coding",
    tagline: "Open-source AI coding assistant plugin",
    description: "Continue is a free, open-source VS Code and JetBrains plugin that lets you connect any LLM to your editor — Ollama, Claude, GPT-4, and more.",
    pricing: "Free (open source)",
    pricingTier: "free",
    rating: 8.5,
    features: ["Bring your own LLM", "VS Code + JetBrains", "Context providers", "Custom slash commands", "Self-hosted option"],
    url: "https://continue.dev",
    affiliate: false,
    featured: false
  },
  {
    id: "claude-code",
    name: "Claude Code",
    category: "coding",
    tagline: "Agentic AI for complex engineering tasks",
    description: "Claude Code is Anthropic's CLI coding agent that autonomously writes, debugs, tests, and commits code. Exceptional for multi-step engineering workflows.",
    pricing: "Usage-based (~$20+/mo)",
    pricingTier: "paid",
    rating: 9.5,
    features: ["Autonomous code agent", "Multi-file edits", "Git integration", "Web research", "Runs in terminal"],
    url: "https://claude.ai/code",
    affiliate: false,
    featured: true
  },

  // ── IMAGE ──────────────────────────────────────────────────
  {
    id: "midjourney",
    name: "Midjourney",
    category: "image",
    tagline: "The gold standard for AI art generation",
    description: "Midjourney produces stunning, highly artistic images from text prompts. Known for its aesthetic quality and active Discord community.",
    pricing: "From $10/mo",
    pricingTier: "paid",
    rating: 9.5,
    features: ["V6 model", "Vary & remix tools", "Style tuning", "Web editor", "Fast GPU priority"],
    url: "https://www.midjourney.com",
    affiliate: false,
    featured: false
  },
  {
    id: "dalle3",
    name: "DALL-E 3",
    category: "image",
    tagline: "OpenAI's photorealistic image generator",
    description: "DALL-E 3 generates detailed, photorealistic images from natural language — built into ChatGPT Plus and available via API. Great for precise prompt following.",
    pricing: "Included in ChatGPT Plus ($20/mo)",
    pricingTier: "paid",
    rating: 8.8,
    features: ["Natural language prompts", "Photorealism", "ChatGPT integration", "API access", "No content restrictions (within policy)"],
    url: "https://openai.com/dall-e-3",
    affiliate: false,
    featured: false
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    category: "image",
    tagline: "Free, open-source image generation",
    description: "Stable Diffusion is the open-source foundation behind countless AI image tools. Run it locally for free, fine-tune on your own images, and use it commercially.",
    pricing: "Free (self-hosted)",
    pricingTier: "free",
    rating: 8.9,
    features: ["Completely free", "Local execution", "Thousands of models (Civitai)", "ControlNet", "Img2Img"],
    url: "https://stability.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    category: "image",
    tagline: "Commercial-safe AI art from Adobe",
    description: "Adobe Firefly is trained on licensed content, making it safe for commercial use. Deeply integrated with Photoshop, Illustrator, and Express.",
    pricing: "Free (25 credits/mo) / From $4.99/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["Commercially safe", "Photoshop Generative Fill", "Text to vector", "3D to image", "Style match"],
    url: "https://firefly.adobe.com",
    affiliate: false,
    featured: false
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    category: "image",
    tagline: "Design + AI in one platform",
    description: "Canva's AI features include text-to-image, Magic Edit, Background Remover, and Magic Resize — making it the all-in-one tool for non-designers.",
    pricing: "Free / Canva Pro $15/mo",
    pricingTier: "freemium",
    rating: 8.7,
    features: ["Magic Edit", "Background Remover", "Text to Image", "Magic Resize", "Brand Kit"],
    url: "https://www.canva.com/ai-image-generator/",
    affiliate: false,
    featured: false
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    category: "image",
    tagline: "Game assets and concept art platform",
    description: "Leonardo AI is tailored for game developers and concept artists, with fine-tuned models for character design, environments, and consistent asset creation.",
    pricing: "Free (150 tokens/day) / From $12/mo",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["Game asset models", "Image guidance (ControlNet)", "AI Canvas", "Real-time generation", "Custom model training"],
    url: "https://leonardo.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "ideogram",
    name: "Ideogram",
    category: "image",
    tagline: "AI that actually renders text in images",
    description: "Ideogram solves the AI typography problem — it reliably renders readable text inside images, making it ideal for logos, posters, and social media graphics.",
    pricing: "Free (10 slow/day) / From $8/mo",
    pricingTier: "freemium",
    rating: 8.5,
    features: ["Text rendering in images", "Magic Prompt enhancement", "Style presets", "Canvas editor", "Upscaler"],
    url: "https://ideogram.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "playground-ai",
    name: "Playground AI",
    category: "image",
    tagline: "Powerful free AI image playground",
    description: "Playground AI offers 500 free images/day using Playground v3 and Stable Diffusion models, with an intuitive canvas editor for creative exploration.",
    pricing: "Free (500 images/day) / From $15/mo",
    pricingTier: "freemium",
    rating: 8.2,
    features: ["500 free daily images", "Canvas editor", "Inpainting", "Multiple models", "Community gallery"],
    url: "https://playground.com",
    affiliate: false,
    featured: false
  },
  {
    id: "nightcafe",
    name: "NightCafe",
    category: "image",
    tagline: "AI art creation with a thriving community",
    description: "NightCafe lets you generate AI art using multiple models and earn free credits by participating in daily challenges. Great for casual creators.",
    pricing: "Free (limited) / From $5.99/mo",
    pricingTier: "freemium",
    rating: 7.8,
    features: ["Multiple AI models", "Credit system", "Daily challenges", "Print-on-demand", "Community gallery"],
    url: "https://nightcafe.studio",
    affiliate: false,
    featured: false
  },
  {
    id: "bing-image-creator",
    name: "Bing Image Creator",
    category: "image",
    tagline: "Free DALL-E 3 images from Microsoft",
    description: "Bing Image Creator gives you DALL-E 3-powered image generation for free, integrated directly into Bing Chat. No subscription required.",
    pricing: "Free",
    pricingTier: "free",
    rating: 8.0,
    features: ["Powered by DALL-E 3", "Completely free", "Bing Chat integration", "Microsoft Designer integration", "No watermarks"],
    url: "https://www.bing.com/images/create",
    affiliate: false,
    featured: false
  },

  // ── VIDEO ──────────────────────────────────────────────────
  {
    id: "runwayml",
    name: "Runway",
    category: "video",
    tagline: "Leading AI video generation platform",
    description: "Runway's Gen-3 model generates cinematic video from text and images. Trusted by filmmakers and creators for its quality and creative control.",
    pricing: "Free (125 credits) / From $15/mo",
    pricingTier: "freemium",
    rating: 9.2,
    features: ["Gen-3 Alpha model", "Text to video", "Image to video", "Video to video", "Motion brush"],
    url: "https://runwayml.com",
    affiliate: false,
    featured: false
  },
  {
    id: "pika-labs",
    name: "Pika",
    category: "video",
    tagline: "Fast and fun AI video creation",
    description: "Pika turns text, images, and video into short AI-generated clips. Known for its speed and playful style controls — popular for social media content.",
    pricing: "Free (limited) / From $8/mo",
    pricingTier: "freemium",
    rating: 8.5,
    features: ["Text to video", "Modify region", "Lip sync", "Sound effects AI", "Fast generation"],
    url: "https://pika.art",
    affiliate: false,
    featured: false
  },
  {
    id: "synthesia",
    name: "Synthesia",
    category: "video",
    tagline: "AI avatar video creation at scale",
    description: "Synthesia creates professional training and explainer videos using AI avatars and text-to-speech — no camera, studio, or actors required.",
    pricing: "From $29/mo",
    pricingTier: "paid",
    rating: 8.9,
    features: ["160+ AI avatars", "130+ languages", "Custom avatar creation", "Screen recorder", "SCORM export"],
    url: "https://www.synthesia.io",
    affiliate: false,
    featured: false
  },
  {
    id: "heygen",
    name: "HeyGen",
    category: "video",
    tagline: "AI video translation and avatar studio",
    description: "HeyGen's video translation feature lip-syncs your videos into 40+ languages with your own voice cloned. Also creates talking AI avatar presentations.",
    pricing: "Free (1 credit) / From $29/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["Video translation (40+ langs)", "Voice cloning", "AI avatars", "Instant avatar", "API access"],
    url: "https://www.heygen.com",
    affiliate: false,
    featured: false
  },
  {
    id: "luma-ai",
    name: "Luma Dream Machine",
    category: "video",
    tagline: "High-quality video from image or text",
    description: "Luma's Dream Machine produces smooth, high-quality short videos with impressive motion and physics. Standout for image-to-video quality.",
    pricing: "Free (30 generations/mo) / From $9.99/mo",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["Image to video", "Text to video", "Loop generation", "Camera controls", "Fast rendering"],
    url: "https://lumalabs.ai/dream-machine",
    affiliate: false,
    featured: false
  },
  {
    id: "descript",
    name: "Descript",
    category: "video",
    tagline: "Edit video by editing transcript text",
    description: "Descript transcribes your video and lets you edit it like a document — delete filler words, overdub your voice, add captions, and publish to YouTube.",
    pricing: "Free / From $24/mo",
    pricingTier: "freemium",
    rating: 9.1,
    features: ["Edit-by-transcript", "Overdub voice cloning", "Filler word removal", "Auto captions", "Screen recorder"],
    url: "https://www.descript.com",
    affiliate: false,
    featured: false
  },
  {
    id: "kapwing",
    name: "Kapwing",
    category: "video",
    tagline: "AI video editor for creators",
    description: "Kapwing is a browser-based video editor with AI features like auto-subtitles, background removal, noise cancellation, and smart crop for repurposing content.",
    pricing: "Free / From $24/mo",
    pricingTier: "freemium",
    rating: 8.3,
    features: ["Auto subtitles", "Background removal", "Smart crop (9:16)", "Noise cancellation", "Team collaboration"],
    url: "https://www.kapwing.com",
    affiliate: false,
    featured: false
  },
  {
    id: "invideo-ai",
    name: "InVideo AI",
    category: "video",
    tagline: "Text-to-video for content marketers",
    description: "InVideo AI converts articles, scripts, or topics into publish-ready videos with stock footage, voiceover, and music — fully automated.",
    pricing: "Free (limited) / From $20/mo",
    pricingTier: "freemium",
    rating: 8.1,
    features: ["Text to video", "16M+ stock media", "AI voiceover", "Auto music sync", "YouTube direct publish"],
    url: "https://invideo.io",
    affiliate: false,
    featured: false
  },
  {
    id: "pictory",
    name: "Pictory",
    category: "video",
    tagline: "Repurpose articles and blogs into video",
    description: "Pictory automatically converts long-form content — blog posts, webinars, Zoom recordings — into short, shareable videos with captions and B-roll.",
    pricing: "From $23/mo",
    pricingTier: "paid",
    rating: 8.2,
    features: ["Article to video", "Blog to video", "Auto highlights", "Caption burns", "Stock library"],
    url: "https://pictory.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "kling-ai",
    name: "Kling AI",
    category: "video",
    tagline: "Cinematic AI video from China's Kuaishou",
    description: "Kling AI produces cinematic, physics-accurate AI video rivaling Runway. Its character consistency and motion quality are standout features in 2026.",
    pricing: "Free (limited) / From $8/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["5-second to 10-second videos", "High motion quality", "Character consistency", "Camera controls", "Lip sync"],
    url: "https://klingai.com",
    affiliate: false,
    featured: false
  },

  // ── MARKETING ──────────────────────────────────────────────────
  {
    id: "semrush",
    name: "Semrush",
    category: "marketing",
    tagline: "All-in-one SEO and marketing intelligence",
    description: "Semrush is the most comprehensive SEO and marketing platform — keyword research, site audits, competitor analysis, and content optimization in one tool.",
    pricing: "From $139/mo",
    pricingTier: "paid",
    rating: 9.3,
    features: ["Keyword research", "Site audit", "Competitor gap analysis", "Content marketing toolkit", "Link building"],
    url: "https://www.semrush.com",
    affiliate: false,
    featured: false
  },
  {
    id: "surfer-seo",
    name: "Surfer SEO",
    category: "marketing",
    tagline: "AI SEO content optimizer",
    description: "Surfer SEO analyzes the top-ranking pages for your target keyword and gives you a real-time content score as you write — the fastest way to SEO-optimize articles.",
    pricing: "From $89/mo",
    pricingTier: "paid",
    rating: 9.0,
    features: ["Content Score", "SERP analyzer", "Keyword research", "Internal linker", "AI article writer"],
    url: "https://surferseo.com",
    affiliate: false,
    featured: false
  },
  {
    id: "marketmuse",
    name: "MarketMuse",
    category: "marketing",
    tagline: "AI content planning and strategy",
    description: "MarketMuse identifies content gaps, scores topic authority, and prioritizes which articles will move the needle most for your site's SEO.",
    pricing: "Free (limited) / From $149/mo",
    pricingTier: "paid",
    rating: 8.6,
    features: ["Topic authority score", "Content gap analysis", "First draft AI", "Competitive benchmarking", "Content briefs"],
    url: "https://www.marketmuse.com",
    affiliate: false,
    featured: false
  },
  {
    id: "adcreative-ai",
    name: "AdCreative.ai",
    category: "marketing",
    tagline: "AI-generated ad creatives that convert",
    description: "AdCreative.ai generates hundreds of conversion-optimized ad images and copy variations in minutes, scored by an AI trained on ad performance data.",
    pricing: "From $29/mo",
    pricingTier: "paid",
    rating: 8.4,
    features: ["Conversion-scored creatives", "Social ad formats", "Text generation", "Background remover", "Team collaboration"],
    url: "https://www.adcreative.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "hubspot-ai",
    name: "HubSpot AI",
    category: "marketing",
    tagline: "AI embedded in the #1 marketing platform",
    description: "HubSpot's AI assistants help with email copy, blog drafts, social posts, and CRM data — all within the HubSpot ecosystem most marketing teams already use.",
    pricing: "Free (basic) / From $20/mo",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["AI email writer", "Blog assistant", "Social copy", "AI chatbot builder", "Predictive lead scoring"],
    url: "https://www.hubspot.com/artificial-intelligence",
    affiliate: false,
    featured: false
  },
  {
    id: "perplexity-pages",
    name: "Perplexity Pages",
    category: "marketing",
    tagline: "AI-researched content marketing pages",
    description: "Perplexity Pages lets you publish well-researched, cited content pages from a single query — useful for building topical authority content at scale.",
    pricing: "Free / Perplexity Pro $20/mo",
    pricingTier: "freemium",
    rating: 8.0,
    features: ["Cited sources", "One-click pages", "Real-time web data", "Shareable URLs", "Embed support"],
    url: "https://www.perplexity.ai/page",
    affiliate: false,
    featured: false
  },
  {
    id: "brandwatch",
    name: "Brandwatch",
    category: "marketing",
    tagline: "AI social listening and brand intelligence",
    description: "Brandwatch monitors brand mentions, sentiment, and trends across social media and the web — AI-powered consumer intelligence for enterprise marketing teams.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.5,
    features: ["Sentiment analysis", "Trend detection", "Influencer ID", "Crisis alerts", "Share of voice"],
    url: "https://www.brandwatch.com",
    affiliate: false,
    featured: false
  },
  {
    id: "mailchimp-ai",
    name: "Mailchimp AI",
    category: "marketing",
    tagline: "AI email marketing for small businesses",
    description: "Mailchimp's AI features predict optimal send times, suggest subject lines, auto-segment audiences, and generate email content for small business marketers.",
    pricing: "Free (500 contacts) / From $13/mo",
    pricingTier: "freemium",
    rating: 8.2,
    features: ["Send-time optimization", "Subject line helper", "Content optimizer", "Predictive segments", "A/B testing"],
    url: "https://mailchimp.com/features/ai/",
    affiliate: false,
    featured: false
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    category: "marketing",
    tagline: "The SEO tool professionals trust most",
    description: "Ahrefs has the largest backlink index in the industry and AI-powered features for keyword research, content gap analysis, and rank tracking.",
    pricing: "From $129/mo",
    pricingTier: "paid",
    rating: 9.2,
    features: ["Largest backlink database", "Keyword Explorer", "Content Gap", "Rank Tracker", "Site Audit"],
    url: "https://ahrefs.com",
    affiliate: false,
    featured: false
  },
  {
    id: "klaviyo-ai",
    name: "Klaviyo AI",
    category: "marketing",
    tagline: "AI email & SMS for ecommerce brands",
    description: "Klaviyo's AI predicts customer lifetime value, auto-generates flows, and optimizes send timing — the marketing automation platform for DTC brands.",
    pricing: "Free (250 contacts) / From $20/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["Predictive CLV", "AI flow generation", "Smart send time", "Subject line AI", "Segment suggestions"],
    url: "https://www.klaviyo.com",
    affiliate: false,
    featured: false
  },

  // ── SALES ──────────────────────────────────────────────────
  {
    id: "gong",
    name: "Gong",
    category: "sales",
    tagline: "Revenue intelligence from your calls",
    description: "Gong records, transcribes, and analyzes sales calls to surface deal risks, coaching opportunities, and winning behaviors across your sales team.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 9.4,
    features: ["Call recording & analysis", "Deal intelligence", "Pipeline risk alerts", "Coaching insights", "Forecast AI"],
    url: "https://www.gong.io",
    affiliate: false,
    featured: false
  },
  {
    id: "apollo-io",
    name: "Apollo.io",
    category: "sales",
    tagline: "Sales prospecting and engagement platform",
    description: "Apollo combines a 275M+ contact database with AI sequencing, email scoring, and intent data — an all-in-one prospecting platform at a fraction of competitor prices.",
    pricing: "Free / From $59/mo",
    pricingTier: "freemium",
    rating: 9.1,
    features: ["275M+ contacts", "AI email sequences", "Intent data", "CRM sync", "LinkedIn extension"],
    url: "https://www.apollo.io",
    affiliate: false,
    featured: false
  },
  {
    id: "clay",
    name: "Clay",
    category: "sales",
    tagline: "AI-powered prospecting enrichment",
    description: "Clay enriches prospect lists by pulling data from 75+ sources and letting AI write personalized outreach based on that data — automating research-heavy SDR work.",
    pricing: "Free / From $149/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["75+ data sources", "AI row enrichment", "Personalized outreach", "Waterfall enrichment", "HubSpot & Salesforce sync"],
    url: "https://www.clay.com",
    affiliate: false,
    featured: false
  },
  {
    id: "lavender",
    name: "Lavender",
    category: "sales",
    tagline: "AI email coach for cold outreach",
    description: "Lavender scores your cold emails in real-time and suggests improvements proven to increase reply rates. Integrates directly into Gmail and Outlook.",
    pricing: "Free / From $29/mo",
    pricingTier: "freemium",
    rating: 8.7,
    features: ["Real-time email scoring", "Personalization suggestions", "Mobile preview", "Gmail & Outlook", "Reply rate benchmarks"],
    url: "https://www.lavender.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "outreach",
    name: "Outreach",
    category: "sales",
    tagline: "AI sales execution platform",
    description: "Outreach is the leading sales engagement platform with AI features for email sequencing, call scoring, pipeline management, and deal forecasting.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.8,
    features: ["AI email sequences", "Deal intelligence", "Kaia meeting AI", "Pipeline management", "Revenue forecasting"],
    url: "https://www.outreach.io",
    affiliate: false,
    featured: false
  },
  {
    id: "salesloft",
    name: "Salesloft",
    category: "sales",
    tagline: "Revenue orchestration for enterprise sales",
    description: "Salesloft unifies cadence, conversations, and forecasting into one platform, with AI coaching that surfaces next-best-action recommendations for reps.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.7,
    features: ["Rhythm AI prioritization", "Conversation intelligence", "Forecasting", "Deal rooms", "CRM integration"],
    url: "https://salesloft.com",
    affiliate: false,
    featured: false
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    category: "sales",
    tagline: "AI meeting notes and transcription",
    description: "Otter.ai joins your Zoom, Teams, or Google Meet calls and produces real-time transcripts, summaries, and action items — automatically shared with the team.",
    pricing: "Free / From $16.99/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["Real-time transcription", "AI meeting summary", "Action item extraction", "Zoom/Teams/Meet integration", "Search transcripts"],
    url: "https://otter.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "chorus-ai",
    name: "Chorus.ai (ZoomInfo)",
    category: "sales",
    tagline: "Conversation intelligence for sales teams",
    description: "Chorus records and analyzes sales conversations, scoring reps on talk ratio, questions asked, and next steps — integrated into ZoomInfo's data platform.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.5,
    features: ["Call recording & scoring", "Deal intelligence", "Coaching playlists", "CRM auto-logging", "ZoomInfo data"],
    url: "https://www.chorus.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "smartlead",
    name: "Smartlead.ai",
    category: "sales",
    tagline: "Unlimited email warmup and cold outreach",
    description: "Smartlead gives you unlimited mailboxes, AI-generated email sequences, and built-in warmup — everything needed to run cold email campaigns at scale without burning domains.",
    pricing: "From $39/mo",
    pricingTier: "paid",
    rating: 8.8,
    features: ["Unlimited mailboxes", "AI email sequences", "Email warmup", "Unified master inbox", "Agency white-label"],
    url: "https://www.smartlead.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "instantly-ai",
    name: "Instantly.ai",
    category: "sales",
    tagline: "Cold email platform with unlimited sending",
    description: "Instantly.ai offers unlimited email accounts, automated warmup, and AI-personalized sequences — making it a go-to for agencies running cold email at volume.",
    pricing: "From $37/mo",
    pricingTier: "paid",
    rating: 8.9,
    features: ["Unlimited sending accounts", "Warmup pool (1M+ accounts)", "AI personalization", "Analytics dashboard", "Agency accounts"],
    url: "https://instantly.ai",
    affiliate: false,
    featured: false
  },

  // ── SUPPORT ──────────────────────────────────────────────────
  {
    id: "intercom-ai",
    name: "Intercom Fin AI",
    category: "support",
    tagline: "AI agent that resolves 50%+ of support tickets",
    description: "Intercom's Fin AI agent resolves customer questions autonomously using your knowledge base — with a human handoff fallback. Charges per resolution, not per seat.",
    pricing: "From $0.99/resolution + base plan",
    pricingTier: "paid",
    rating: 9.2,
    features: ["Autonomous resolution", "Multi-language", "Omnichannel (chat/email)", "Human handoff", "Knowledge base sync"],
    url: "https://www.intercom.com/fin",
    affiliate: false,
    featured: false
  },
  {
    id: "zendesk-ai",
    name: "Zendesk AI",
    category: "support",
    tagline: "AI built into the world's #1 support platform",
    description: "Zendesk AI auto-classifies tickets, suggests responses, auto-summarizes conversations, and routes issues to the right agent — reducing handle time significantly.",
    pricing: "Add-on to Zendesk plans (from $55/agent/mo)",
    pricingTier: "paid",
    rating: 9.0,
    features: ["Auto-classification", "Suggested replies", "AI summarization", "Smart routing", "Agent Copilot"],
    url: "https://www.zendesk.com/platform/ai/",
    affiliate: false,
    featured: false
  },
  {
    id: "tidio",
    name: "Tidio",
    category: "support",
    tagline: "AI chatbot for small business customer support",
    description: "Tidio's Lyro AI resolves up to 70% of customer questions automatically using your FAQ and knowledge base. Easy to set up for Shopify and WooCommerce stores.",
    pricing: "Free / From $29/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["Lyro AI agent", "Shopify integration", "Live chat fallback", "Product recommendations", "50+ languages"],
    url: "https://www.tidio.com",
    affiliate: false,
    featured: false
  },
  {
    id: "freshdesk-ai",
    name: "Freshdesk Freddy AI",
    category: "support",
    tagline: "Freddy AI for smarter customer support",
    description: "Freshdesk's Freddy AI suggests responses, auto-triages tickets, and provides a self-service bot — built into the Freshdesk helpdesk most SMBs use.",
    pricing: "Free (10 agents) / From $15/agent/mo",
    pricingTier: "freemium",
    rating: 8.4,
    features: ["Freddy Self Service bot", "Auto-triage", "Suggested replies", "Sentiment detection", "CSAT prediction"],
    url: "https://www.freshworks.com/freshdesk/freddy-ai/",
    affiliate: false,
    featured: false
  },
  {
    id: "chatbase",
    name: "Chatbase",
    category: "support",
    tagline: "Build a ChatGPT chatbot from your docs",
    description: "Chatbase lets you upload PDFs, docs, and website URLs to train a custom AI chatbot — embed it on your website in minutes with no coding.",
    pricing: "Free / From $19/mo",
    pricingTier: "freemium",
    rating: 8.5,
    features: ["Upload any source", "Website embed", "Customizable chat UI", "Lead capture", "Zapier integration"],
    url: "https://www.chatbase.co",
    affiliate: false,
    featured: false
  },
  {
    id: "ada",
    name: "Ada",
    category: "support",
    tagline: "Enterprise AI customer service automation",
    description: "Ada's AI agent handles complex customer service interactions across chat, phone, and email — with deep integrations to backend systems for automated resolutions.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.8,
    features: ["Multi-channel AI", "Backend integrations", "Automated resolutions", "Escalation management", "Analytics"],
    url: "https://www.ada.cx",
    affiliate: false,
    featured: false
  },
  {
    id: "helpscout-ai",
    name: "Help Scout AI",
    category: "support",
    tagline: "AI-powered help desk for growing teams",
    description: "Help Scout's AI features summarize conversations, draft replies, and suggest knowledge base articles — while maintaining the human feel customers prefer.",
    pricing: "From $22/user/mo",
    pricingTier: "paid",
    rating: 8.7,
    features: ["AI Summarize", "AI Drafts", "Article Recommendations", "Docs AI search", "Customer profiles"],
    url: "https://www.helpscout.com",
    affiliate: false,
    featured: false
  },
  {
    id: "kustomer",
    name: "Kustomer",
    category: "support",
    tagline: "AI CRM for customer service teams",
    description: "Kustomer unifies customer history from all channels into one timeline, with AI that deflects tickets, suggests responses, and auto-closes resolved conversations.",
    pricing: "From $89/user/mo",
    pricingTier: "paid",
    rating: 8.6,
    features: ["360° customer view", "AI deflection", "Omnichannel inbox", "AI suggested replies", "Workflow automation"],
    url: "https://www.kustomer.com",
    affiliate: false,
    featured: false
  },
  {
    id: "forethought",
    name: "Forethought",
    category: "support",
    tagline: "Generative AI for enterprise support",
    description: "Forethought's Solve AI auto-resolves Tier-1 tickets while Assist AI provides reps with the context and suggested responses they need in real time.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.9,
    features: ["Auto-resolution", "Agent Assist AI", "Ticket routing", "Sentiment analysis", "Zendesk/Salesforce integration"],
    url: "https://forethought.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "voiceflow",
    name: "Voiceflow",
    category: "support",
    tagline: "Build and deploy AI agents without code",
    description: "Voiceflow is a visual platform for building AI voice and chat agents — from simple FAQ bots to complex support flows with API integrations and conditional logic.",
    pricing: "Free / From $50/mo",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["Visual agent builder", "Voice + chat", "API integrations", "KnowledgeBase AI", "Team collaboration"],
    url: "https://www.voiceflow.com",
    affiliate: false,
    featured: false
  },

  // ── DATA ──────────────────────────────────────────────────
  {
    id: "julius-ai",
    name: "Julius AI",
    category: "data",
    tagline: "Chat with your data, get insights instantly",
    description: "Julius lets you upload CSV files and ask questions in plain English — it writes and runs the analysis code automatically, returning charts and summaries.",
    pricing: "Free / From $25/mo",
    pricingTier: "freemium",
    rating: 8.9,
    features: ["Natural language queries", "Auto chart generation", "Python/R code execution", "CSV/Excel upload", "Shareable reports"],
    url: "https://julius.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "tableau-ai",
    name: "Tableau AI (Einstein)",
    category: "data",
    tagline: "AI-powered business intelligence",
    description: "Tableau's Einstein AI features include natural language questions, predictive forecasting, and anomaly detection — built into the world's most popular BI tool.",
    pricing: "From $75/user/mo",
    pricingTier: "paid",
    rating: 9.0,
    features: ["Ask Data (NL queries)", "Explain Data", "Forecast modeling", "Anomaly detection", "Salesforce integration"],
    url: "https://www.tableau.com/products/tableau-ai",
    affiliate: false,
    featured: false
  },
  {
    id: "datarobot",
    name: "DataRobot",
    category: "data",
    tagline: "Enterprise AutoML and AI platform",
    description: "DataRobot automates the entire machine learning lifecycle — data prep, model training, deployment, and monitoring — for enterprise data teams.",
    pricing: "Custom (enterprise)",
    pricingTier: "enterprise",
    rating: 8.8,
    features: ["AutoML", "MLOps monitoring", "Explainable AI", "No-code option", "Multi-cloud deployment"],
    url: "https://www.datarobot.com",
    affiliate: false,
    featured: false
  },
  {
    id: "obviously-ai",
    name: "Obviously AI",
    category: "data",
    tagline: "No-code ML predictions in minutes",
    description: "Obviously AI builds predictive models from spreadsheets with no coding — predict churn, LTV, sales, and more with a point-and-click interface.",
    pricing: "From $75/mo",
    pricingTier: "paid",
    rating: 8.2,
    features: ["No-code ML", "CSV upload", "Churn/LTV prediction", "API deployment", "Explainability dashboard"],
    url: "https://www.obviously.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "akkio",
    name: "Akkio",
    category: "data",
    tagline: "Generative AI analytics for agencies",
    description: "Akkio's Chat Data Prep and AI forecasting tools let marketing agencies and analysts build predictive models and generate reports from conversational prompts.",
    pricing: "From $49/mo",
    pricingTier: "paid",
    rating: 8.4,
    features: ["Chat Data Prep", "No-code forecasting", "CRM integrations", "Auto-reports", "Agency client portals"],
    url: "https://www.akkio.com",
    affiliate: false,
    featured: false
  },
  {
    id: "hex",
    name: "Hex",
    category: "data",
    tagline: "Collaborative AI notebook for data teams",
    description: "Hex is a SQL + Python notebook with AI Magic that generates, fixes, and explains code. Teams collaborate in real time on analyses and publish interactive apps.",
    pricing: "Free / From $24/user/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["AI Magic (generate SQL/Python)", "Real-time collaboration", "Interactive app publishing", "Data warehouse integrations", "Version history"],
    url: "https://hex.tech",
    affiliate: false,
    featured: false
  },
  {
    id: "polymer-search",
    name: "Polymer",
    category: "data",
    tagline: "AI-powered spreadsheet explorer",
    description: "Polymer transforms raw spreadsheet data into an interactive, searchable app with AI-generated insights — no BI tool setup required.",
    pricing: "Free / From $20/mo",
    pricingTier: "freemium",
    rating: 8.0,
    features: ["Drag-and-drop dashboards", "AI chart suggestions", "Searchable data apps", "Share via link", "Google Sheets sync"],
    url: "https://www.polymersearch.com",
    affiliate: false,
    featured: false
  },
  {
    id: "microsoft-fabric",
    name: "Microsoft Fabric AI",
    category: "data",
    tagline: "Unified analytics platform with Copilot",
    description: "Microsoft Fabric unifies data lake, data warehouse, and BI into one platform with Copilot AI — natural language to SQL, data prep automation, and Power BI integration.",
    pricing: "From $262.80/month (capacity)",
    pricingTier: "paid",
    rating: 8.7,
    features: ["Copilot in Power BI", "Data lakehouse", "SQL generation", "Data pipeline AI", "OneLake"],
    url: "https://www.microsoft.com/en-us/microsoft-fabric",
    affiliate: false,
    featured: false
  },
  {
    id: "metabase",
    name: "Metabase",
    category: "data",
    tagline: "Open-source BI with natural language queries",
    description: "Metabase is an open-source BI tool with a natural language query interface — ask questions about your database in plain English without writing SQL.",
    pricing: "Free (self-hosted) / Cloud from $500/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["NL query (Ask Metabase)", "Open source", "SQL + visual editors", "Self-hosted option", "Embeddable dashboards"],
    url: "https://www.metabase.com",
    affiliate: false,
    featured: false
  },
  {
    id: "deepnote",
    name: "Deepnote",
    category: "data",
    tagline: "AI data notebook for collaborative teams",
    description: "Deepnote is a collaborative data science notebook with AI that generates SQL, Python, and visualizations — real-time collaboration like Google Docs for data.",
    pricing: "Free / From $12/user/mo",
    pricingTier: "freemium",
    rating: 8.5,
    features: ["AI code generation", "Real-time collaboration", "SQL + Python + R", "Data warehouse connections", "App publishing"],
    url: "https://deepnote.com",
    affiliate: false,
    featured: false
  },

  // ── AUTOMATION ──────────────────────────────────────────────────
  {
    id: "zapier-ai",
    name: "Zapier",
    category: "automation",
    tagline: "Connect 7,000+ apps with AI-powered workflows",
    description: "Zapier is the no-code automation leader — AI helps you build Zaps from plain English descriptions. Zapier Agents can even take actions across your apps autonomously.",
    pricing: "Free (100 tasks/mo) / From $29.99/mo",
    pricingTier: "freemium",
    rating: 9.3,
    features: ["7,000+ app integrations", "AI Zap builder", "Zapier Agents", "Tables + Interfaces", "Paths (conditional logic)"],
    url: "https://zapier.com",
    affiliate: false,
    featured: false
  },
  {
    id: "make",
    name: "Make (formerly Integromat)",
    category: "automation",
    tagline: "Visual automation with unlimited flexibility",
    description: "Make's visual builder handles complex, multi-step workflows with branching logic, iterators, and data transformers — far more powerful than Zapier for technical users.",
    pricing: "Free (1,000 ops/mo) / From $9/mo",
    pricingTier: "freemium",
    rating: 9.1,
    features: ["Visual scenario builder", "1,500+ app connections", "Data mapping", "Error handling", "Webhooks"],
    url: "https://www.make.com",
    affiliate: false,
    featured: false
  },
  {
    id: "n8n",
    name: "n8n",
    category: "automation",
    tagline: "Open-source workflow automation for developers",
    description: "n8n is a self-hostable automation tool with 400+ integrations and AI nodes for LLMs — giving developers full control over their automation stack.",
    pricing: "Free (self-hosted) / Cloud from $24/mo",
    pricingTier: "freemium",
    rating: 9.0,
    features: ["Open source / self-hosted", "400+ integrations", "AI / LLM nodes", "Code nodes", "Fair-code license"],
    url: "https://n8n.io",
    affiliate: false,
    featured: false
  },
  {
    id: "activepieces",
    name: "Activepieces",
    category: "automation",
    tagline: "Open-source Zapier alternative with AI",
    description: "Activepieces is a fully open-source automation tool with an AI piece for integrating LLMs directly into your flows — a great free alternative to Zapier.",
    pricing: "Free (self-hosted) / Cloud from $0",
    pricingTier: "free",
    rating: 8.5,
    features: ["Fully open source", "AI piece (GPT-4, Claude)", "Visual builder", "100+ integrations", "Self-hostable"],
    url: "https://www.activepieces.com",
    affiliate: false,
    featured: false
  },
  {
    id: "bardeen",
    name: "Bardeen",
    category: "automation",
    tagline: "AI browser automation with one click",
    description: "Bardeen automates repetitive browser tasks — scraping, form filling, and data transfer — using AI that learns from what you do on screen.",
    pricing: "Free / From $10/mo",
    pricingTier: "freemium",
    rating: 8.4,
    features: ["Browser automation", "AI Magic Actions", "Scraper", "CRM data push", "Chrome extension"],
    url: "https://www.bardeen.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "relay-app",
    name: "Relay.app",
    category: "automation",
    tagline: "Collaborative automation with human-in-the-loop",
    description: "Relay.app is a modern workflow automation tool designed for human-AI collaboration — you can pause automations for human review at any step.",
    pricing: "Free / From $29/mo",
    pricingTier: "freemium",
    rating: 8.6,
    features: ["Human-in-the-loop steps", "AI steps (GPT, Claude)", "100+ integrations", "Collaborative workflow", "Approval gates"],
    url: "https://www.relay.app",
    affiliate: false,
    featured: false
  },
  {
    id: "lindy-ai",
    name: "Lindy AI",
    category: "automation",
    tagline: "Personal AI employee for any workflow",
    description: "Lindy builds AI employees (Lindies) that autonomously handle tasks like email triage, meeting scheduling, CRM updates, and customer follow-ups.",
    pricing: "From $49.99/mo",
    pricingTier: "paid",
    rating: 8.7,
    features: ["Autonomous AI agents", "Email AI", "Calendar AI", "CRM auto-updates", "Trigger-based flows"],
    url: "https://www.lindy.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "uipath",
    name: "UiPath",
    category: "automation",
    tagline: "Enterprise RPA + AI automation platform",
    description: "UiPath is the leading robotic process automation (RPA) platform — combining UI bots with AI to automate complex enterprise workflows across any system.",
    pricing: "Free (Community) / Enterprise custom",
    pricingTier: "freemium",
    rating: 8.9,
    features: ["RPA bots", "AI computer vision", "Document understanding", "Process mining", "Orchestrator"],
    url: "https://www.uipath.com",
    affiliate: false,
    featured: false
  },
  {
    id: "power-automate",
    name: "Microsoft Power Automate",
    category: "automation",
    tagline: "Microsoft's automation platform with Copilot",
    description: "Power Automate connects Microsoft 365 apps and thousands of external services with AI Copilot that builds flows from plain English — included in Microsoft 365.",
    pricing: "From $15/user/mo (standalone)",
    pricingTier: "paid",
    rating: 8.6,
    features: ["Microsoft 365 native", "AI Copilot builder", "RPA desktop flows", "Process Advisor", "Approvals module"],
    url: "https://powerautomate.microsoft.com",
    affiliate: false,
    featured: false
  },
  {
    id: "paperclip-ai",
    name: "Paperclip AI",
    category: "automation",
    tagline: "AI agent company operating system",
    description: "Paperclip AI is a multi-agent operating system where AI agents have roles, budgets, and task queues — autonomously running your business operations 24/7.",
    pricing: "See pricing",
    pricingTier: "paid",
    rating: 9.3,
    features: ["Multi-agent workforce", "Task management", "Agent budgets & roles", "Heartbeat execution", "Human oversight"],
    url: "https://paperclip.ing",
    affiliate: false,
    featured: true
  },

  // ── PRODUCTIVITY ──────────────────────────────────────────────────
  {
    id: "notion-ai-prod",
    name: "Notion AI",
    category: "productivity",
    tagline: "AI inside your all-in-one workspace",
    description: "Notion AI drafts documents, summarizes meeting notes, extracts action items, and answers questions from your entire Notion workspace — context-aware and fast.",
    pricing: "$10/mo add-on",
    pricingTier: "paid",
    rating: 8.9,
    features: ["Workspace Q&A", "AI drafts", "Translate", "Action items", "Summary generator"],
    url: "https://www.notion.so/product/ai",
    affiliate: false,
    featured: false
  },
  {
    id: "mem-ai",
    name: "Mem.ai",
    category: "productivity",
    tagline: "AI-powered memory for your notes",
    description: "Mem is an AI note-taking app that auto-organizes your notes and learns your context over time — surface related ideas and get AI answers from your personal knowledge base.",
    pricing: "From $14.99/mo",
    pricingTier: "paid",
    rating: 8.1,
    features: ["Auto-organization", "AI search", "Smart collections", "Captures anywhere", "Bi-directional links"],
    url: "https://mem.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "reclaim-ai",
    name: "Reclaim AI",
    category: "productivity",
    tagline: "Smart scheduling for busy professionals",
    description: "Reclaim AI automatically finds the best time for your tasks, habits, and meetings on Google Calendar — protecting focus time while keeping your schedule sane.",
    pricing: "Free / From $10/user/mo",
    pricingTier: "freemium",
    rating: 8.8,
    features: ["Auto task scheduling", "Habit protection", "Smart meeting scheduling", "Buffer time", "Google Calendar sync"],
    url: "https://reclaim.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "motion",
    name: "Motion",
    category: "productivity",
    tagline: "AI project manager + calendar in one",
    description: "Motion automatically schedules all your tasks, meetings, and projects into the optimal daily plan — rescheduling in real time when priorities change.",
    pricing: "From $34/mo",
    pricingTier: "paid",
    rating: 8.7,
    features: ["Auto-schedule tasks", "Project management", "Meeting scheduling", "Daily plan optimization", "Team coordination"],
    url: "https://www.usemotion.com",
    affiliate: false,
    featured: false
  },
  {
    id: "superhuman",
    name: "Superhuman AI",
    category: "productivity",
    tagline: "The fastest email experience + AI",
    description: "Superhuman is a premium email client with AI that writes replies, summarizes threads, and triages your inbox — built for people who get 100+ emails a day.",
    pricing: "From $30/mo",
    pricingTier: "paid",
    rating: 8.6,
    features: ["AI email drafts", "Thread summaries", "Keyboard-driven", "Split inbox", "Read statuses"],
    url: "https://superhuman.com",
    affiliate: false,
    featured: false
  },
  {
    id: "elicit",
    name: "Elicit",
    category: "productivity",
    tagline: "AI research assistant for literature review",
    description: "Elicit searches and summarizes academic papers for you — extract key findings, compare methodologies, and build evidence tables from research literature in minutes.",
    pricing: "Free / From $10/mo",
    pricingTier: "freemium",
    rating: 8.5,
    features: ["Academic paper search", "Findings extraction", "Evidence tables", "Data synthesis", "Citation export"],
    url: "https://elicit.com",
    affiliate: false,
    featured: false
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    category: "productivity",
    tagline: "AI search with cited, real-time answers",
    description: "Perplexity answers questions with real-time web sources, cited references, and follow-up suggestions — a faster, more accurate alternative to traditional search.",
    pricing: "Free / Pro $20/mo",
    pricingTier: "freemium",
    rating: 9.2,
    features: ["Real-time web search", "Cited answers", "File analysis", "Collections", "API access"],
    url: "https://www.perplexity.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "rewind-ai",
    name: "Rewind AI",
    category: "productivity",
    tagline: "AI memory for everything you've seen",
    description: "Rewind records your screen and audio locally, making everything searchable and summarizable — find any meeting, conversation, or document from your past.",
    pricing: "From $20/mo",
    pricingTier: "paid",
    rating: 8.3,
    features: ["Local recording (private)", "Universal search", "Meeting summaries", "Ask Rewind AI", "Mac-native"],
    url: "https://www.rewind.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "claude",
    name: "Claude",
    category: "productivity",
    tagline: "Anthropic's AI assistant for complex thinking",
    description: "Claude excels at long-context analysis, nuanced writing, coding, and reasoning — a go-to AI assistant for professionals who need depth over speed.",
    pricing: "Free / Claude Pro $20/mo",
    pricingTier: "freemium",
    rating: 9.4,
    features: ["200K token context", "Deep reasoning", "File analysis", "Artifacts (mini-apps)", "API access"],
    url: "https://claude.ai",
    affiliate: false,
    featured: false
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "productivity",
    tagline: "The world's most-used AI assistant",
    description: "ChatGPT with GPT-4o handles writing, research, coding, data analysis, and image generation — the most versatile AI assistant available today.",
    pricing: "Free / Plus $20/mo",
    pricingTier: "freemium",
    rating: 9.3,
    features: ["GPT-4o model", "Image generation (DALL-E)", "Code interpreter", "Custom GPTs", "Voice mode"],
    url: "https://chat.openai.com",
    affiliate: false,
    featured: false
  }
];

// Category metadata for UI rendering
const CATEGORIES = [
  { id: "writing",      label: "Writing",      icon: "✍️",  count: 10, desc: "AI writing tools, copywriting, grammar, and content generation" },
  { id: "coding",       label: "Coding",       icon: "💻",  count: 10, desc: "AI code assistants, pair programmers, and developer tools" },
  { id: "image",        label: "Image",        icon: "🎨",  count: 10, desc: "AI image generators, editors, and creative design tools" },
  { id: "video",        label: "Video",        icon: "🎬",  count: 10, desc: "AI video creation, editing, avatars, and translation tools" },
  { id: "marketing",    label: "Marketing",    icon: "📈",  count: 10, desc: "SEO, ad creatives, email marketing, and growth AI tools" },
  { id: "sales",        label: "Sales",        icon: "💼",  count: 10, desc: "Sales intelligence, prospecting, and outreach automation" },
  { id: "support",      label: "Support",      icon: "🎧",  count: 10, desc: "AI customer support, chatbots, and helpdesk automation" },
  { id: "data",         label: "Data",         icon: "📊",  count: 10, desc: "Data analysis, BI, AutoML, and analytics AI tools" },
  { id: "automation",   label: "Automation",   icon: "⚡",  count: 10, desc: "No-code workflow automation, RPA, and AI agent platforms" },
  { id: "productivity", label: "Productivity", icon: "🚀",  count: 10, desc: "AI assistants, scheduling, note-taking, and focus tools" }
];
